"""OpenSCAD source generation and command execution."""

from pathlib import Path
import subprocess
from .models import BoardGeometry, GenerationParameters, Point, Polyline


class OpenSCADExecutionError(RuntimeError):
    """OpenSCAD is missing, failed, or did not produce the requested STL."""


def _point(point: Point) -> str:
    return f"[{point.x:.5f}, {point.y:.5f}]"


def _trace_module(
    trace: Polyline, width: float, height: float, base_thickness: float
) -> str:
    points = trace.points + ((trace.points[0],) if trace.closed else ())
    lines = [
        f"    // trace trench with {len(points)} points",
        # Extrude starting at (base_thickness - height) and overshoot top by 0.1mm
        # to ensure clean manifold boolean subtraction without coplanar face artifacts
        f"    translate([0, 0, {(base_thickness - height):.5f}])",
        f"      linear_extrude(height={(height + 0.1):.5f})",
        "      union() {",
    ]
    for first, second in zip(points, points[1:]):
        lines.extend([
            "        hull() {",
            f"          translate({_point(first)}) circle(d={width:.5f}, $fn=24);",
            f"          translate({_point(second)}) circle(d={width:.5f}, $fn=24);",
            "        }",
        ])
    lines.append("      }")
    return "\n".join(lines)


def generate_openscad(geometry: BoardGeometry, parameters: GenerationParameters) -> str:
    """Return a self-contained OpenSCAD program in millimetres."""
    parameters.validate()
    # Connect trace trench endpoints directly to through-hole centers
    board = geometry.connect_traces_to_holes(parameters.snap_tolerance).translated_to_origin()
    width, depth = board.size
    if width <= 0 or depth <= 0:
        raise ValueError("Outline must span a positive width and height")
    margin = parameters.outline_margin
    width += margin * 2
    depth += margin * 2
    shift = lambda point: Point(point.x + margin, point.y + margin)

    source = [
        "// Generated by pcb3d; units are millimetres.",
        f"base_thickness = {parameters.base_thickness:.5f};",
        f"trace_height = {parameters.trace_height:.5f};",
        f"trace_width = {parameters.trace_width:.5f};",
        "",
        "difference() {",
        f"  cube([{width:.5f}, {depth:.5f}, base_thickness]);",
        "  union() {",
    ]
    for hole in board.holes:
        center = shift(hole.center)
        source.extend([
            f"    translate([{center.x:.5f}, {center.y:.5f}, -0.1]) "
            f"cylinder(h=base_thickness + 0.2, r={hole.radius:.5f}, $fn=48);",
        ])
    for trace in board.traces:
        shifted = Polyline(tuple(shift(point) for point in trace.points), trace.closed)
        source.append(_trace_module(
            shifted,
            parameters.trace_width,
            parameters.trace_height,
            parameters.base_thickness,
        ))
    source.extend(["  }", "}", ""])
    return "\n".join(source)



def run_openscad(
    source: str,
    output_stl: str | Path,
    *,
    executable: str = "openscad",
    work_directory: str | Path | None = None,
) -> Path:
    """Write source, run OpenSCAD, and return a verified STL path."""
    output = Path(output_stl)
    output.parent.mkdir(parents=True, exist_ok=True)
    source_path = output.with_suffix(".scad")
    source_path.write_text(source, encoding="utf-8")
    command = [executable, "-o", str(output), str(source_path)]
    try:
        result = subprocess.run(
            command,
            cwd=work_directory,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        raise OpenSCADExecutionError(
            f"Unable to execute OpenSCAD '{executable}': {exc}"
        ) from exc
    if result.returncode != 0:
        details = (result.stderr or result.stdout).strip()
        raise OpenSCADExecutionError(
            f"OpenSCAD failed with exit code {result.returncode}: {details or 'no details'}"
        )
    if not output.is_file() or output.stat().st_size == 0:
        raise OpenSCADExecutionError(f"OpenSCAD completed but produced no STL at '{output}'")
    return output
